jobtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls'))

]

tracker/urls.py
from django.contrib import admin
from django.urls import path
from .views import InterviewCreateView, JobCreateView, JobDetailView, JobListView, JobSearch, rejectedView

urlpatterns = [
    
    path('', JobListView.as_view(), name="job-list"),
    path('Jobs/add/', JobCreateView.as_view(), name='job-create'),
    path('Jobs/search', JobSearch.as_view(), name="job-search"),
    path('Jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('Jobs/<int:pk>/AddInterview/', InterviewCreateView.as_view(), name="add-interview"),
    path('Jobs/<int:pk>/Rejected' , rejectedView, name='job-rejected'),
]

tracker/models.py
from django.db import models
from django.utils import timezone

class Job(models.Model):
    position_name = models.CharField(max_length=250)
    company_name = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    date_applied = models.DateTimeField(default=timezone.now)
    applied_via = models.CharField(max_length=200)
    rejected = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.position_name} @ {self.company_name}'

class Interview(models.Model):
    interview_date = models.DateTimeField()
    interviewer = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    thoughts = models.TextField(null=True, blank=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

tracker/views.py
from django.shortcuts import render, redirect
import pkg_resources
from .models import Job, Interview
from django.views.generic import View, CreateView
from django.urls import reverse, reverse_lazy
from django.db.models import Count, Q
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

# Create your views here.
class JobListView(View):
    def get(self, request, *args, **kwargs):
        jobs = Job.objects.all().order_by('-date_applied')
        interviews = Job.objects.annotate(num_of_interviews=Count('interview'))

        context = {
            'jobs':jobs,
            
        }

        return render(request, 'tracker/jobs.html', context=context)

class JobCreateView(SuccessMessageMixin, CreateView):
    model = Job
    fields=['position_name', 'company_name', 'location', 'applied_via']
    success_message = "Job added, Good luck"
    template_name: 'job_form.html'
    # returning redirect to job list after job is added
    def get_success_url(self):
        return reverse('job-list')

class JobDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        job = Job.objects.get(pk=pk)
        interviews = Interview.objects.filter(job=job)

        context ={
            'job':job,
            'interviews':interviews
        }

        return render(request, 'tracker/job_detail.html', context)


class JobSearch(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('query')
        job_list = Job.objects.filter(Q(position_name__icontains=query))

        context = {
            'job_list':job_list
        }

        return render(request, 'tracker/search.html', context)

class InterviewCreateView(SuccessMessageMixin, CreateView):
    model = Interview
    fields=['interview_date', 'interviewer', 'type', 'thoughts', ]
    success_message = "Interview added, Good luck"
    template_name: 'interview_form.html'


    def form_valid(self, form):
        form.instance.job_id = self.kwargs['pk']
        return super(InterviewCreateView, self).form_valid(form)

    # returning redirect to job list after job is added
    def get_success_url(self):
            return reverse('job-detail', args=[self.kwargs['pk']])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prev_job'] = self.kwargs['pk']
        return context

#view to change boolean of "rejected" in DB model
def rejectedView(request, pk, *args, **kwargs):
    try:
        job = Job.objects.get(pk=pk)

        #checking if i was already rejected and setting accordingly
        if job.rejected == True:
            job.rejected = False
        else:
            job.rejected = True

        job.save()
        messages.success(request, f'You didnt want to work for {job.company_name} anyway!')
        return redirect('job-list')
    except:
        messages.error(request, f'Something went wrong')
        return ('jobs/{pk}')

tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Job Tracker</title>
    </head>
    <body>
        {% block content%} {% endblock %}

    <!--Bootstrap stuff-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/Javascript" src="{% static 'js/blog.js' %}"></script>
 

    </body>
</html>

tracker/templates/jobs.html
{% extends tracker/base.html %}
{% block content %}
{% for job in jobs %}

<article class="media content-section position-relative">
    <div class="media-body">
        <h5> {{ job.company_name }} </h5>
        <h6> {{ job.position_name }}</h6>
        <p>Interviews:</p>
    </div>
</article>
{% endblock content %}

tracker/templates/tracker/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    <link rel="stylesheet" type="text/css" href="{% static 'tracker/main.css' %}">
    <title>Job Tracker</title>

    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">Job Tracker</a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
                      
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'job-list' %}">Home</a>
                      </li> 
    
                      <li class="nav-item active">
                        <a class="nav-item nav-link" href="{% url 'job-create' %}">Add job</a>
                      </li>
                    </ul>
                        <form id="search" class ="form-inline my-2 my-lg-0" method="GET" action="{% url 'job-search' %}">
                          <div class="input-group d-flex align-items-center">
                            
                            <input type="text" class="form-control mr-sm-2" placeholder="Search Jobs" aria-label="Job" aria-describedby="basic-addon1"
                            name="query" value="{{ request.GET.query }}">
                            
                            <div class="input-group-append">
                            <input value="Search" class="btn btn-outline-success my-2 my-sm-0 btn-sm mt-2" type="submit"></input>
                            </div>

                          </div>
                        </form>
                      
                    </ul>
                </div>
              </div>
            </nav>
        
            <main class="container">
              <div class="row flex-nowrap">
                <div class="col-md-8">
                  {% if messages %}
                    {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}"> 
                        {{ message }}
                      </div>
                    {% endfor %}
                  
                  {% endif %}
      
                  {% block content %}{% endblock %}
                </div>

    <!--Bootstrap stuff--> 

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
</html>

tracker/templates/tracker/interview_form.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}
{% block content %} 
   <div class="form-group mt-2">
         <a class="btn btn-outline-info mb-3" href="{% url 'job-detail' prev_job %}" >Back to job</a>
    </div>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Create post
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group mt-3">
                <button class="btn btn-success" type="submit"> Add Interview </button>
            </div>
        </form>
    </div>
    <script>
        const urlParams = new URLSearchParams(window.location)
        const pk_of_job = urlParams.get('pk')
       
    </script>
{% endblock content %}

tracker/templates/tracker/job_detail.html
{% extends 'tracker/base.html' %}
{% block content %}

<article class="media content-section">
    <div class="media-body">
        Position: {{ job.position_name }} <br>
        Company: {{ job.company_name }} <br>
        <small class="text-muted"> Applied: {{ job.date_applied|date:"M d, Y" }} via {{ job.applied_via }}</small>
        <p> Location: {{ job.location }}</p>
    </div>
    <div class="d-flex justify-content-between">
    <form action="{% url 'add-interview' job.pk %}" >
        <button type="submit" value="{{job.pk}}" class="btn btn-sm btn-success">Add Interview</button>
    </form>
    <form action="{% url 'job-rejected' job.pk %}" >
        {% if job.rejected %}
        <button class="btn btn-outline-success btn-sm ">Back in the running</button>
        {% else %}
        <button class="btn btn-outline-danger btn-sm">Rejected</button>
        {% endif %}
    </form>
    </div>
</article>
{% if interviews %}
<h5>Interviews:</h5>
{% endif %}
    {% for interview in interviews %}
    <div class="card mb-2">
        <div class="card-body">
    <h4 class="card-title"> Interviewer: {{ interview.interviewer }}</h4>
    <p class="card-subtitle mb-2 text-muted" > {{ interview.interview_date|date:"M d, Y" }}</p>
    <p class="card-text">{{ interview.thoughts }}</p>
        </div>
    </div>
{% endfor %}
{% endblock content %}

tracker/templates/tracker/job_form.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}
{% block content %}    
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Create post
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit"> Add Job </button>
            </div>
        </form>
    </div>
{% endblock content %}

tracker/templates/tracker/jobs.html
{% extends 'tracker/base.html' %}
{% block content %}

<style>
    tr[data-href]{
        cursor:pointer;
    }
</style>
<h1>Jobs Applied for: {{jobs.count}}</h1>

<table class="table table-striped table-hover">
    <thead class="thead-light">
        <tr>

            <th scope="col"> Company </th>
            <th scope="col"> Position </th>
            <th scope="col"> # Interviews </th>
            <th scope="col"> Status? </th>
        </tr>
    </thead>
    <tbody>
        {% for job in jobs %}
        {% if job.rejected %}
        <tr data-href="{% url 'job-detail' job.pk %}" class="table-danger">
        {% else %}
        <tr data-href="{% url 'job-detail' job.pk %}" >
        {% endif %}
            <td> {{ job.company_name }}</td>
            <td> {{ job.position_name }}</td>
            <td> {{job.interview_set.all|length}} </td>
            <td>
                {% if job.rejected %}
                <span>X</span>
                {% else %}
                <span>?</span>
                {% endif %}
            </td>
        </tr>

        {% endfor %}
    </tbody>
</table>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const rows = document.querySelectorAll("tr[data-href]");
        rows.forEach( row => {
            row.addEventListener("click", () => {
                window.location.href = row.dataset.href;
            })
        })

    })
</script>

{% endblock content %}

tracker/templates/tracker/search.html
{% extends "tracker/base.html" %}

{% block content %} 

<div class="container">
    {% for job in job_list %}
        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12 border-bottom position-relative">
                <p>{{ job.position_name }} @ {{ job.company_name }}</p>
                <small class="text-muted sm">Applied on: {{ job.date_applied }}</small>

            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}